/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: '#f7faf8',
        'on-background': '#181c1b',
        surface: '#f7faf8',
        'surface-dim': '#d8dbd9',
        'surface-bright': '#f7faf8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f2',
        'surface-container': '#eceeed',
        'surface-container-high': '#e6e9e7',
        'surface-container-highest': '#e0e3e1',
        'on-surface': '#181c1b',
        'on-surface-variant': '#3d4948',
        'inverse-surface': '#2d3130',
        'inverse-on-surface': '#eef1ef',
        outline: '#6d7a78',
        'outline-variant': '#bcc9c7',
        'surface-tint': '#006a66',
        primary: '#006763',
        'on-primary': '#ffffff',
        'primary-container': '#00837e',
        'on-primary-container': '#f3fffd',
        'inverse-primary': '#5fd9d2',
        secondary: '#625e56',
        'on-secondary': '#ffffff',
        'secondary-container': '#e9e1d7',
        'on-secondary-container': '#68645c',
        tertiary: '#5d5c58',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#767471',
        'on-tertiary-container': '#fcffe3',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#7ef6ee',
        'primary-fixed-dim': '#5fd9d2',
        'on-primary-fixed': '#00201e',
        'on-primary-fixed-variant': '#00504d',
        'secondary-fixed': '#e9e1d7',
        'secondary-fixed-dim': '#ccc6bc',
        'on-secondary-fixed': '#1e1b15',
        'on-secondary-fixed-variant': '#4a463f',
        'tertiary-fixed': '#e5e2dd',
        'tertiary-fixed-dim': '#c9c6c2',
        'on-tertiary-fixed': '#1c1c19',
        'on-tertiary-fixed-variant': '#474743'
      },
      fontFamily: {
        sans: ['Hanken Grotesk', 'sans-serif'],
      },
      borderRadius: {
        '2xl': '16px',
        '3xl': '24px',
      },
      spacing: {
        'safe-margin': '20px',
      }
    },
  },
  plugins: [],
}
